/**
 * Central Data Store for Kohli Samaj Web Portal
 * Structured for seamless backend integration with C# .NET Web API / MVC models.
 */

const initialData = {
    settings: {
        currentLang: 'en',
        fontSize: 'normal' // 'small', 'normal', 'large'
    },
    stats: [
        { id: 1, icon: 'fa-house-chimney', number: '518', label_en: 'Villages', label_mr: 'गावे', note_en: 'Community-reported figure', note_mr: 'समाज-नोंदणीकृत आकडेवारी' },
        { id: 2, icon: 'fa-location-dot', number: '5', label_en: 'Key Districts', label_mr: 'प्रमुख जिल्हे', note_en: 'Bhandara, Gondia, Gadchiroli, Chandrapur, Balaghat', note_mr: 'भंडारा, गोंदिया, गडचिरोली, चंद्रपूर, बालाघाट' },
        { id: 3, icon: 'fa-users', number: 'Lakhs+', label_en: 'Community Members', label_mr: 'समाज बांधव', note_en: 'Across Vidarbha & Urban Centers', note_mr: 'विदर्भ व शहरी भागातील' },
        { id: 4, icon: 'fa-city', number: 'Nagpur, Pune, Mumbai', label_en: 'Urban & Industrial Centers', label_mr: 'प्रमुख शहरी व औद्योगिक केंद्रे', note_en: 'Education, Employment & Business', note_mr: 'शिक्षण, नोकरी व व्यवसाय' }
    ],
    notices: [
        {
            id: 0,
            title_en: 'Historical Census Records & Upcoming India Census 2027 Information',
            title_mr: 'ऐतिहासिक जनगणना नोंदी व आगामी भारतीय जनगणना २०२७ माहिती',
            date: '2026-08-01',
            location: 'All Districts (भंडारा, गोंदिया, चंद्रपूर, गडचिरोली)',
            category: 'Census 2027',
            details_en: 'Official census information regarding historical demographic archives (1881–1931) and current administrative processes for Census 2027 initiated by the Government of India.',
            details_mr: 'ऐतिहासिक जनगणना नोंदी (१८८१-१९३१) आणि भारत सरकारद्वारे सुरू करण्यात आलेल्या जनगणना २०२७ च्या प्रशासकीय प्रक्रियेची अधिकृत माहिती.'
        },
        {
            id: 1,
            title_en: 'Kohli Samaj Grand Convention (Melava) - 15 June 2026, Bhandara',
            title_mr: 'समाज मेळावा - १५ जून २०२६, भंडारा',
            date: '2026-06-15',
            location: 'Bhandara, Maharashtra',
            category: 'Event',
            details_en: 'Annual grand gathering of the Kohli community discussing agricultural advancements, water conservation projects, and youth empowerment.',
            details_mr: 'कोहळी समाजाचा वार्षिक भव्य मेळावा ज्यामध्ये शेती प्रगती, जलसंवर्धन प्रकल्प आणि युवक सक्षमीकरणावर चर्चा होणार आहे.'
        },
        {
            id: 2,
            title_en: 'State Level Educational Guidance & Career Camp - 22 June 2026',
            title_mr: 'शैक्षणिक मार्गदर्शन शिबीर - २२ जून २०२६',
            date: '2026-06-22',
            location: 'Nagpur & Online',
            category: 'Education',
            details_en: 'Career counseling and scholarship guidance session for Kohli Samaj students preparing for competitive exams and higher education.',
            details_mr: 'स्पर्धा परीक्षा व उच्च शिक्षणासाठी तयारी करणाऱ्या कोहळी समाजातील विद्यार्थ्यांसाठी करिअर समुपदेशन व शिष्यवृत्ती मार्गदर्शन सत्र.'
        },
        {
            id: 3,
            title_en: 'Matrimonial Meet (Vadhu-Var Parichay Melava) - Registration Open',
            title_mr: 'वधू-वर परिचय मेळावा - नोंदणी सुरू',
            date: '2026-07-10',
            location: 'Chandrapur',
            category: 'Matrimonial',
            details_en: 'Registrations are now open for the upcoming Vadhu-Var Parichay Melava. Submit candidate profiles online or via local district representatives.',
            details_mr: 'आगामी वधू-वर परिचय मेळाव्यासाठी नोंदणी सुरू झाली आहे. ऑनलाईन किंवा स्थानिक जिल्हा प्रतिनिधींमार्फत उमेदवारांची माहिती सादर करा.'
        }
    ],
    pillars: [
        {
            id: 'history',
            title_en: 'Our History',
            title_mr: 'आपला इतिहास',
            desc_en: 'The origin, heritage, traditions, and historic journey of the Kohli community across centuries in Central India.',
            desc_mr: 'कोहळी समाजाचा उगम, इतिहास, परंपरा आणि मध्य भारतातील ऐतिहासिक प्रवास.',
            image: 'images/history_arch.jpg'
        },
        {
            id: 'water',
            title_en: 'Water Conservation Heritage',
            title_mr: 'जलसंवर्धन वारसा',
            desc_en: 'Pioneers of Malguzari tanks, bhandaras, and indigenous irrigation networks of Vidarbha region.',
            desc_mr: 'तलाव, बंधारे, सिंचन व्यवस्था आणि जलव्यवस्थापनातील अमूल्य योगदान.',
            image: 'images/water_lake.jpg'
        },
        {
            id: 'culture',
            title_en: 'Culture & Traditions',
            title_mr: 'संस्कृती व परंपरा',
            desc_en: 'Rich festivals, folk traditions, marriage customs, and unique social harmony of Kohli culture.',
            desc_mr: 'परंपरा, सण, उत्सव, विवाह पद्धती आणि आपल्या संस्कृतीची ओळख.',
            image: 'images/culture_tradition.jpg'
        },
        {
            id: 'documents',
            title_en: 'Historical Documents',
            title_mr: 'ऐतिहासिक दस्तऐवज',
            desc_en: 'Archival gazetteers, settlement reports, British census records, and official heritage publications.',
            desc_mr: 'जनगणना, गॅझेटियर, सेटलमेंट रिपोर्ट आणि अन्य महत्त्वाचे ऐतिहासिक संदर्भ.',
            image: 'images/document_scroll.jpg'
        }
    ],
    timeline: [
        {
            id: 1,
            year: '1867',
            category_en: 'Historical Publication',
            category_mr: 'ऐतिहासिक प्रकाशन',
            icon: 'fa-book',
            title_en: 'Central Provinces Historical References',
            title_mr: 'Central Provinces Historical References',
            desc_en: 'Historical references from the Central Provinces period provide context on communities, administration and social organization. Such records are used as part of the historical study of the Kohli community.',
            desc_mr: '1867 च्या Central Provinces संदर्भांमध्ये या प्रदेशातील विविध समुदाय, सामाजिक रचना आणि प्रशासनाशी संबंधित नोंदी आढळतात. उपलब्ध समुदाय संशोधनात या काळातील संदर्भांचा उपयोग कोहळी समाजाच्या ऐतिहासिक अभ्यासासाठी केला जातो.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 2,
            year: '1870',
            category_en: 'Settlement Report',
            category_mr: 'सेटलमेंट रिपोर्ट',
            icon: 'fa-map',
            title_en: 'Chanda Settlement Report',
            title_mr: 'Chanda Settlement Report',
            desc_en: 'The Chanda Settlement Report contains historical references concerning the Kohli/Kohri community, including population, agriculture, sugarcane cultivation, tanks and aspects of social life.',
            desc_mr: 'चांदा जिल्ह्याच्या Settlement Report मध्ये कोहळी/कोहरी समुदायासंबंधी लोकसंख्या, शेती, ऊस लागवड, तलाव आणि सामाजिक जीवनाचे संदर्भ आढळतात.',
            source_en: 'Chanda Settlement Report — Settlement-era administrative record',
            source_mr: 'Chanda Settlement Report — Settlement-era administrative record'
        },
        {
            id: 3,
            year: '1881',
            category_en: 'Census',
            category_mr: 'जनगणना',
            icon: 'fa-users',
            title_en: 'Census of India — Historical Census Reference',
            title_mr: 'Census of India — Historical Census Reference',
            desc_en: 'The 1881 Census of India forms part of the historical census series used to study population and community records in the Central Provinces region.',
            desc_mr: '1881 च्या Census of India मध्ये तत्कालीन प्रशासकीय प्रदेशातील विविध समुदाय आणि लोकसंख्येची नोंद करण्यात आली. कोहळी समाजाच्या ऐतिहासिक लोकसंख्या अभ्यासासाठी ही जनगणना मालिका महत्त्वाची संदर्भशृंखला आहे.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 4,
            year: '1887',
            category_en: 'Gazetteer',
            category_mr: 'गॅझेटिअर',
            icon: 'fa-book-open',
            title_en: 'Imperial Gazetteer of India',
            title_mr: 'Imperial Gazetteer of India',
            desc_en: 'The Imperial Gazetteer of India provides historical information about regions, communities, economy and administration. The supplied research material uses references from this period in studying Kohli/Kohri history.',
            desc_mr: 'Imperial Gazetteer of India मधील संदर्भांमध्ये तत्कालीन भारतातील प्रदेश, समाज, अर्थव्यवस्था आणि प्रशासनाविषयी माहिती आढळते. उपलब्ध समुदाय संशोधनात कोहळी/कोहरी संदर्भांसाठी या काळातील नोंदींचा उपयोग केला जातो.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 5,
            year: '1891',
            category_en: 'Census',
            category_mr: 'जनगणना',
            icon: 'fa-users',
            title_en: 'Census of India — Historical Census Reference',
            title_mr: 'Census of India — Historical Census Reference',
            desc_en: 'The 1891 Census forms part of the historical census series relevant to studying population and administrative records relating to the Kohli community.',
            desc_mr: '1891 ची जनगणना ही कोहळी समाजाच्या ऐतिहासिक लोकसंख्या आणि प्रशासकीय नोंदींच्या अभ्यासासाठी महत्त्वाच्या जनगणना मालिकेतील एक नोंद आहे.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 6,
            year: '1901',
            category_en: 'Census',
            category_mr: 'जनगणना',
            icon: 'fa-users',
            title_en: 'Census of India — Historical Census Reference',
            title_mr: 'Census of India — Historical Census Reference',
            desc_en: 'The 1901 Census provides historical demographic and social classification context for the Central Provinces.',
            desc_mr: '1901 च्या जनगणनेतील नोंदी तत्कालीन मध्य प्रांतातील लोकसंख्या आणि सामाजिक वर्गीकरणाचा अभ्यास करण्यासाठी ऐतिहासिक संदर्भ म्हणून वापरल्या जातात.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 7,
            year: '1909',
            category_en: 'Gazetteer',
            category_mr: 'गॅझेटिअर',
            icon: 'fa-book-open',
            title_en: 'Chanda / Chandrapur District Gazetteer',
            title_mr: 'Chanda / Chandrapur District Gazetteer',
            desc_en: 'The Chanda/Chandrapur District Gazetteer provides historical information about the region\'s communities, agriculture, water resources and administration, including references used in studying the Kohli community.',
            desc_mr: 'चांदा जिल्हा गॅझेटिअरमधील संदर्भांमध्ये प्रदेशातील समाजजीवन, शेती, जलस्रोत आणि प्रशासनासंबंधी ऐतिहासिक माहिती आढळते. कोहळी समाजाविषयी उपलब्ध संदर्भ या व्यापक ऐतिहासिक पार्श्वभूमीत अभ्यासले जातात.',
            source_en: 'Historical reference',
            source_mr: 'Historical reference'
        },
        {
            id: 8,
            year: '1911',
            category_en: 'Statistical Record',
            category_mr: 'सांख्यिकीय नोंद',
            icon: 'fa-file-signature',
            title_en: 'Historical Bhandara Population Record',
            title_mr: 'Historical Bhandara Population Record',
            desc_en: '<div style="font-size:2.5rem; font-weight:800; color:var(--primary-dark); margin:0.5rem 0;">11,399</div>According to the historical statistical material supplied from the Central Provinces District Gazetteers, the Kohli population recorded in Bhandara District in the 1911 census was 11,399.<div style="margin-top:0.8rem; padding:0.6rem; background:#fff3cd; border-left:3px solid #ffc107; font-size:0.85rem; color:#856404;">This is a historical district-level figure. Administrative boundaries at that time differed from present-day district boundaries.</div>',
            desc_mr: '<div style="font-size:2.5rem; font-weight:800; color:var(--primary-dark); margin:0.5rem 0;">11,399</div>उपलब्ध Central Provinces District Gazetteers मधील सांख्यिकीय नोंदीनुसार, 1911 च्या जनगणनेत भंडारा जिल्ह्यात कोहळी समाजाची लोकसंख्या 11,399 अशी नोंद आढळते.<div style="margin-top:0.8rem; padding:0.6rem; background:#fff3cd; border-left:3px solid #ffc107; font-size:0.85rem; color:#856404;">हा ऐतिहासिक जिल्हा-आधारित आकडा आहे. त्या काळातील प्रशासकीय सीमा आजच्या जिल्ह्यांच्या सीमांपेक्षा वेगळ्या होत्या.</div>',
            source_en: 'Bhandara District — Central Provinces District Gazetteers, Statistical Tables 1891–1926, corrected up to 1926.',
            source_mr: 'Bhandara District — Central Provinces District Gazetteers, Statistical Tables 1891–1926, corrected up to 1926.'
        },
        {
            id: 9,
            year: '1916',
            category_en: 'Historical Publication',
            category_mr: 'ऐतिहासिक प्रकाशन',
            icon: 'fa-microscope',
            title_en: 'R. V. Russell & Hiralal — The Tribes and Castes of the Central Provinces of India',
            title_mr: 'R. V. Russell & Hiralal — The Tribes and Castes of the Central Provinces of India',
            desc_en: 'R. V. Russell and Hiralal\'s The Tribes and Castes of the Central Provinces of India documents various communities of the Central Provinces. References to Kohli/Kohri communities form part of the historical literature used for community research.',
            desc_mr: 'R. V. Russell आणि Hiralal यांच्या The Tribes and Castes of the Central Provinces of India या ग्रंथामध्ये Central Provinces मधील विविध समुदायांचे ऐतिहासिक, सामाजिक आणि व्यावसायिक वर्णन करण्यात आले आहे. कोहळी/कोहरी संदर्भांसाठी हा ग्रंथ उपलब्ध ऐतिहासिक साहित्याचा एक भाग आहे.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 10,
            year: '1926',
            category_en: 'Statistical Record',
            category_mr: 'सांख्यिकीय नोंद',
            icon: 'fa-file-signature',
            title_en: 'Bhandara District Statistical Tables',
            title_mr: 'Bhandara District Statistical Tables',
            desc_en: 'Available Bhandara District statistical material contains historical statistical records for the 1891–1926 period and provides context for historical population research. (Corrected up to 1926)',
            desc_mr: 'उपलब्ध Bhandara District statistical material मध्ये 1891–1926 या कालखंडातील सांख्यिकीय नोंदी संकलित करण्यात आल्या असून त्या ऐतिहासिक लोकसंख्या अभ्यासासाठी संदर्भ म्हणून उपयोगी आहेत. (Corrected up to 1926)',
            source_en: '',
            source_mr: ''
        },
        {
            id: 11,
            year: '1973',
            category_en: 'Gazetteer',
            category_mr: 'गॅझेटिअर',
            icon: 'fa-book-open',
            title_en: 'Maharashtra State Gazetteer — Chandrapur District, Revised Edition',
            title_mr: 'Maharashtra State Gazetteer — Chandrapur District, Revised Edition',
            desc_en: 'The revised Maharashtra State Gazetteer for Chandrapur District provides historical information on the region\'s history, society, economy, agriculture and administration. Kohli-related references can be studied within this broader regional historical record.',
            desc_mr: 'महाराष्ट्र राज्य गॅझेटिअरच्या चंद्रपूर जिल्ह्याच्या सुधारित आवृत्तीमध्ये प्रदेशाच्या इतिहास, समाज, अर्थव्यवस्था, शेती आणि प्रशासनाविषयी माहिती संकलित करण्यात आली आहे. कोहळी समाजाशी संबंधित उपलब्ध संदर्भ या प्रादेशिक ऐतिहासिक साहित्याचा भाग म्हणून अभ्यासता येतात.',
            source_en: '',
            source_mr: ''
        },
        {
            id: 12,
            year: 'Modern',
            category_en: 'Community Development',
            category_mr: 'समाज विकास',
            icon: 'fa-people-group',
            title_en: 'परंपरेतून आधुनिकतेकडे',
            title_mr: 'परंपरेतून आधुनिकतेकडे',
            desc_en: 'In the post-independence and modern period, members of the Kohli community have expanded into education, business, social organizations, public life, arts, technology and digital media.',
            desc_mr: 'स्वातंत्र्योत्तर काळात आणि विशेषतः आधुनिक काळात कोहळी समाजाने शिक्षण, व्यवसाय, सामाजिक संघटन, सार्वजनिक जीवन, कला, तंत्रज्ञान आणि डिजिटल माध्यमे यांसारख्या विविध क्षेत्रांत वाटचाल केली.',
            source_en: '',
            source_mr: ''
        }
    ],

    // ============================================================
    // HISTORICAL DOCUMENTS DATA
    // ============================================================
    documents: [

    {
        id: 1,
        category: 'settlement',
        year: '1867',
        title_en: 'Central Provinces Gazetteer – Bhandara District Entry',
        title_mr: 'सेंट्रल प्रॉव्हिन्सेस गॅझेटियर – भंडारा जिल्हा नोंद',
        author_en: 'British Imperial Gazetteer of India',
        author_mr: 'ब्रिटिश इम्पेरियल गॅझेटियर ऑफ इंडिया',
        publisher_en: 'Central Provinces Administration, Nagpur',
        publisher_mr: 'सेंट्रल प्रॉव्हिन्सेस प्रशासन, नागपूर',
        language: 'English',
        pages: '412',
        desc_en: 'Foundational British-era gazetteer documenting Kohli Samaj as hereditary Malguzars and master tank-builders in Bhandara district. Contains detailed village-level data on tank ownership, paddy yields, and revenue settlements.',
        desc_mr: 'भंडारा जिल्ह्यातील कोहळी समाजाला वंशपरंपरागत मालगुजार आणि तलाव निर्माते म्हणून नोंदवणारा मूलभूत ब्रिटिश काळातील गॅझेटियर.',
        key_reference_en: '"The Kohlis are the dominant cultivating caste... masters of the tank irrigation system that feeds the entire district."',
        key_reference_mr: '"कोहळी हे प्रमुख शेती जात असून... संपूर्ण जिल्ह्याला पाणी देणाऱ्या तलाव सिंचन व्यवस्थेचे स्वामी आहेत."',
        icon: 'fa-book-open',
        color: '#0e3e29',
        available: false,
        related_page: '#'
    },
    {
        id: 2,
        category: 'settlement',
        year: '1870',
        title_en: 'Chanda District Settlement Report',
        title_mr: 'चांदा जिल्हा सेटलमेंट अहवाल',
        author_en: 'R.V. Russell, ICS – Settlement Officer',
        author_mr: 'आर.व्ही. रसेल, आयसीएस – सेटलमेंट अधिकारी',
        publisher_en: 'Central Provinces Government Press',
        publisher_mr: 'सेंट्रल प्रॉव्हिन्सेस गव्हर्नमेंट प्रेस',
        language: 'English',
        pages: '358',
        desc_en: 'Official settlement records detailing agricultural landholdings, irrigation structures, and village leadership in Chanda. Documents 400+ Kohli-owned tanks and their revenue contribution to colonial administration.',
        desc_mr: 'चांदा मधील शेतजमीन, सिंचन रचना व गाव नेतृत्वाचा तपशील. कोहळी-मालकीच्या ४०० पेक्षा जास्त तलावांचे आणि त्यांच्या महसुलाचे दस्तावेजीकरण.',
        key_reference_en: '"Kohli Malguzars are responsible for constructing and maintaining the earthen bhandaras... without which paddy cultivation would be impossible."',
        key_reference_mr: '"कोहळी मालगुजार मातीचे बंधारे बांधण्यास व देखभालीस जबाबदार आहेत... त्यांच्याशिवाय भात शेती अशक्य असती."',
        icon: 'fa-scroll',
        color: '#7c4700',
        available: false,
        related_page: '#'
    },
    {
        id: 3,
        category: 'census',
        year: '1881',
        title_en: 'Census of India – Central Provinces Volume',
        title_mr: 'सेन्सस ऑफ इंडिया – सेंट्रल प्रॉव्हिन्सेस खंड',
        author_en: 'Census Commissioner, Government of India',
        author_mr: 'जनगणना आयुक्त, भारत सरकार',
        publisher_en: 'Government of India Printing Office',
        publisher_mr: 'भारत सरकार मुद्रणालय',
        language: 'English',
        pages: '620',
        desc_en: 'The first detailed demographic census of Central Provinces documenting Kohli community population, occupational patterns, and socio-economic status.',
        desc_mr: 'सेंट्रल प्रॉव्हिन्सेसची पहिली सविस्तर जनगणना ज्यामध्ये कोहळी समाजाची लोकसंख्या, व्यवसाय आणि सामाजिक-आर्थिक स्थिती नोंदवलेली आहे.',
        key_reference_en: '"The Kohlis are an industrious agricultural community, distinguished by their expertise in constructing and maintaining irrigation tanks."',
        key_reference_mr: '"कोहळी हे एक उद्योगशील शेती समुदाय आहेत, जे सिंचन तलाव बांधण्यात आणि देखरेखीत तज्ज्ञ म्हणून प्रसिद्ध आहेत."',
        icon: 'fa-users-rectangle',
        color: '#1a6b8a',
        available: false,
        related_page: '#'
    },
    {
        id: 4,
        category: 'gazetteer',
        year: '1909',
        title_en: 'Chanda Gazetteer – First Edition',
        title_mr: 'चांदा गॅझेटियर – पहिली आवृत्ती',
        author_en: 'R. H. Craddock, C.S.I., Chief Commissioner',
        author_mr: 'आर. एच. क्रॅडॉक, सी.एस.आय., मुख्य आयुक्त',
        publisher_en: 'British India Press, Bombay',
        publisher_mr: 'ब्रिटिश इंडिया प्रेस, मुंबई',
        language: 'English',
        pages: '524',
        desc_en: 'Comprehensive first-edition geographical and historical study of Chanda district. Extensively documents indigenous water engineering by Kohli Malguzars.',
        desc_mr: 'चांदा जिल्ह्याचा सर्वसमावेशक पहिल्या आवृत्तीचा भौगोलिक व ऐतिहासिक अभ्यास. कोहळी मालगुजारांच्या मातीच्या बंधाऱ्यांच्या बांधकाम पद्धतींचे सविस्तर वर्णन.',
        key_reference_en: '"The Kohli Malguzars of Chanda are the backbone of agricultural prosperity... their bhandaras are marvels of indigenous engineering."',
        key_reference_mr: '"चांदाचे कोहळी मालगुजार कृषी समृद्धीचा आधारस्तंभ आहेत... त्यांचे बंधारे स्थानिक अभियांत्रिकीचे आश्चर्य आहेत."',
        icon: 'fa-book-open',
        color: '#5a3e00',
        available: false,
        related_page: '#'
    },
    {
        id: 5,
        category: 'gazetteer',
        year: '1920',
        title_en: 'Bhandara District Gazetteer',
        title_mr: 'भंडारा जिल्हा गॅझेटियर',
        author_en: 'Central Provinces & Berar District Gazetteer Series',
        author_mr: 'सेंट्रल प्रॉव्हिन्सेस व बेरार जिल्हा गॅझेटियर मालिका',
        publisher_en: 'Government Press, Nagpur',
        publisher_mr: 'गव्हर्नमेंट प्रेस, नागपूर',
        language: 'English',
        pages: '498',
        desc_en: 'Detailed district gazetteer covering Bhandara district. Contains a dedicated chapter on "Kohli Malguzars and Tank Irrigation System" documenting 850+ tanks across 142 villages.',
        desc_mr: 'भंडारा जिल्ह्याचा सविस्तर जिल्हा गॅझेटियर. "कोहळी मालगुजार व तलाव सिंचन व्यवस्था" या समर्पित प्रकरणात १४२ गावांमधील ८५०+ तलावांची नोंद.',
        key_reference_en: '"The district owes its agricultural wealth to the Kohli community who have, for generations, constructed and maintained the network of tanks."',
        key_reference_mr: '"जिल्ह्याची शेती संपत्ती कोहळी समाजाची देण आहे ज्यांनी पिढ्यानपिढ्या तलावांचे जाळे बांधले व सांभाळले."',
        icon: 'fa-map',
        color: '#2d6a4f',
        available: false,
        related_page: '#'
    },
    {
        id: 6,
        category: 'settlement',
        year: '1891',
        title_en: 'Bhandara Settlement Report',
        title_mr: 'भंडारा सेटलमेंट अहवाल',
        author_en: 'W.B. Heycock, ICS – Settlement Commissioner',
        author_mr: 'डब्ल्यू.बी. हेकॉक, आयसीएस – सेटलमेंट कमिशनर',
        publisher_en: 'Central Provinces Government Press, Nagpur',
        publisher_mr: 'सेंट्रल प्रॉव्हिन्सेस गव्हर्नमेंट प्रेस, नागपूर',
        language: 'English',
        pages: '284',
        desc_en: 'Comprehensive settlement survey of Bhandara district detailing land revenue, Malguzari rights, and irrigation infrastructure.',
        desc_mr: 'भंडारा जिल्ह्याचा सर्वसमावेशक सेटलमेंट सर्वेक्षण ज्यात जमीन महसूल व्यवस्था, मालगुजारी हक्क आणि सिंचन पायाभूत सुविधांचा तपशील आहे.',
        key_reference_en: '"The Bhandara lakes ... have been maintained exclusively by Kohli Malguzars under hereditary rights."',
        key_reference_mr: '"भंडाऱ्याचे तलाव, वंशपरंपरागत हक्काने कोहळी मालगुजारांनी सांभाळले आहेत."',
        icon: 'fa-scroll',
        color: '#6b3a2a',
        available: false,
        related_page: '#'
    },
    {
        id: 7,
        category: 'census',
        year: '1901',
        title_en: 'Census of India 1901 – Caste & Tribe Descriptions',
        title_mr: 'सेन्सस ऑफ इंडिया १९०१ – जाती व जमात वर्णन',
        author_en: 'R.V. Russell & Hira Lal, Ethnographers',
        author_mr: 'आर.व्ही. रसेल व हिरा लाल, नृवंशशास्त्रज्ञ',
        publisher_en: 'Government of Central Provinces',
        publisher_mr: 'सेंट्रल प्रॉव्हिन्सेस सरकार',
        language: 'English',
        pages: '780',
        desc_en: 'Ethnographic documentation with a dedicated section on Kohli community covering origin legends, occupations, and Malguzari role.',
        desc_mr: 'कोहळी समाजाच्या उत्पत्ती, परंपरा, व्यवसाय व मालगुजारी भूमिकेवर संपूर्ण विभाग.',
        key_reference_en: '"The Kohli claim to be Kshatriyas... their monopoly on tank construction is unrivalled in the Central Provinces."',
        key_reference_mr: '"कोहळी स्वतःला क्षत्रिय म्हणतात... तलाव बांधकामावरील त्यांचे वर्चस्व सेंट्रल प्रॉव्हिन्सेसमध्ये अतुलनीय आहे."',
        icon: 'fa-users-rectangle',
        color: '#1a4a6b',
        available: false,
        related_page: '#'
    },
    {
        id: 8,
        category: 'gazetteer',
        year: '1973',
        title_en: 'Maharashtra State Gazetteer – Bhandara (Revised)',
        title_mr: 'महाराष्ट्र स्टेट गॅझेटियर – भंडारा (सुधारित)',
        author_en: 'Maharashtra State Gazetteer Department',
        author_mr: 'महाराष्ट्र राज्य गॅझेटियर विभाग',
        publisher_en: 'Directorate of Government Printing, Maharashtra',
        publisher_mr: 'सरकारी मुद्रण संचालनालय, महाराष्ट्र',
        language: 'English & Marathi',
        pages: '640',
        desc_en: 'Post‑independence revised state archive formally recognizing traditional water tanks constructed by Kohli Malguzars as heritage structures.',
        desc_mr: 'स्वातंत्र्योत्तर सुधारित राज्य अभिलेख जो कोहळी मालगुजारांनी बांधलेल्या पारंपरिक तलावांना वारसा स्थापत्य म्हणून अधिकृतपणे मान्यता देतो.',
        key_reference_en: '"The Malguzari lakes of Bhandara, largely constructed by the Kohli community, represent one of the finest examples of indigenous water management."',
        key_reference_mr: '"भंडाऱ्याचे मालगुजारी तलाव, मुख्यतः कोहळी समाजाने बांधलेले, स्थानिक जल व्यवस्थापनाचे उत्कृष्ट उदाहरण आहेत."',
        icon: 'fa-landmark',
        color: '#5a1a0a',
        available: false,
        related_page: '#'
    },
    {
        id: 9,
        category: 'publication',
        year: '1985',
        title_en: 'Tribes and Castes of the Central Provinces of India',
        title_mr: 'मध्य प्रांतातील जाती व जमाती',
        author_en: 'R.V. Russell & Hira Lal',
        author_mr: 'आर.व्ही. रसेल व हिरा लाल',
        publisher_en: 'Cosmo Publications, New Delhi (Reprint)',
        publisher_mr: 'कॉस्मो पब्लिकेशन्स, नवी दिल्ली (पुनर्मुद्रण)',
        language: 'English',
        pages: '4 Volumes',
        desc_en: 'Most comprehensive ethnographic study of Central India castes and tribes. The Kohli entry spans 38 pages covering history, mythology, social structure, religious practices, and agricultural innovations.',
        desc_mr: 'मध्य भारतातील जाती व जमातींचा सर्वांत सविस्तर नृवंशशास्त्रीय अभ्यास. कोहळी प्रविष्टी ३८ पाने, ज्यात इतिहास, पुराणशास्त्र, सामाजिक रचना आणि तलाव‑निर्माण परंपरांचा समावेश.',
        key_reference_en: '"The Kohlis are the most skilled tank‑builders in India... their method of constructing earthen bunds is a science refined over centuries."',
        key_reference_mr: '"कोहळी भारतातील सर्वात कुशल तलाव निर्माते आहेत... मातीचे बांध बांधण्याची त्यांची पद्धत शतकांमध्ये परिपूर्ण केलेले विज्ञान आहे."',
        icon: 'fa-microscope',
        color: '#2c3e50',
        available: false,
        related_page: '#'
    },
    {
        id: 10,
        category: 'government',
        year: '1908',
        title_en: 'Gondia District Revenue Survey',
        title_mr: 'गोंदिया जिल्हा महसूल सर्वेक्षण',
        author_en: 'Central Provinces Revenue Department',
        author_mr: 'सेंट्रल प्रॉव्हिन्सेस महसूल विभाग',
        publisher_en: 'Government Press, Nagpur',
        publisher_mr: 'गव्हर्नमेंट प्रेस, नागपूर',
        language: 'English',
        pages: '312',
        desc_en: 'Revenue survey documenting the extraordinary network of 920+ tanks managed by Kohli Malguzars.',
        desc_mr: 'गोंदिया चे महसूल सर्वेक्षण ज्यात कोहळी मालगुजारांनी व्यवस्थापित ९२०+ तलावांच्या असाधारण जाळ्याचे दस्तावेजीकरण.',
        key_reference_en: '"Gondiya has more tanks per square mile than any other district in Central India, all traced to the enterprise of the Kohli Malguzars."',
        key_reference_mr: '"गोंडियामध्ये मध्य भारतातील कोणत्याही जिल्ह्यापेक्षा प्रति चौरस मैल सर्वाधिक तलाव आहेत, जे सर्व कोहळी मालगुजारांच्या उद्यमशीलतेचे फळ आहे."',
        icon: 'fa-water',
        color: '#1a6b5a',
        available: false,
        related_page: '#'
    },
    {
        id: 11,
        category: 'census',
        year: '1931',
        title_en: 'Census of India 1931 – Central Provinces & Berar',
        title_mr: 'सेन्सस ऑफ इंडिया १९३१ – सेंट्रल प्रॉव्हिन्सेस व बेरार',
        author_en: 'J.H. Hutton, Census Commissioner',
        author_mr: 'जे.एच. हटन, जनगणना आयुक्त',
        publisher_en: 'Government of India Press',
        publisher_mr: 'भारत सरकार प्रेस',
        language: 'English',
        pages: '556',
        desc_en: 'Detailed caste tables and socio‑economic data. Documents Kohli population growth and contribution to rice export economy.',
        desc_mr: '१९३१ च्या जनगणनेत जात सारण्या आणि सामाजिक‑आर्थिक डेटा आहे. कोहळी लोकसंख्येची वाढ आणि ब्रिटिश भारताच्या तांदूळ निर्यात अर्थव्यवस्थेतील योगदानाची नोंद.',
        key_reference_en: '"The rice belt of Central Provinces owes its productivity to the ancient irrigation tanks maintained by the Kohli community."',
        key_reference_mr: '"सेंट्रल प्रॉव्हिन्सेसच्या भात पट्ट्याची उत्पादकता कोहळी समाजाने देखभाल केलेल्या प्राचीन सिंचन तलावांमुळे आहे."',
        icon: 'fa-users-rectangle',
        color: '#3a2a6b',
        available: false,
        related_page: '#'
    },
    {
        id: 12,
        category: 'publication',
        year: '2010',
        title_en: 'Malguzari System and Indigenous Water Heritage of Vidarbha',
        title_mr: 'विदर्भातील मालगुजारी व्यवस्था आणि स्थानिक जल वारसा',
        author_en: 'Dr. Ramesh Kohale, Nagpur University',
        author_mr: 'डॉ. रमेश कोहाळे, नागपूर विद्यापीठ',
        publisher_en: 'Vidarbha Heritage Research Publications, Nagpur',
        publisher_mr: 'विदर्भ हेरिटेज रिसर्च पब्लिकेशन्स, नागपूर',
        language: 'Marathi & English',
        pages: '286',
        desc_en: 'Modern scholarly work tracing the history of the Malguzari system with special focus on Kohli community.',
        desc_mr: 'विदर्भातील मालगुजारी व्यवस्थेचा इतिहास मांडणारा आधुनिक विद्वत्पूर्ण ग्रंथ.',
        key_reference_en: 'Documents that Kohli Malguzars constructed over 3,000 tanks across Vidarbha between the 15th and 19th centuries.',
        key_reference_mr: 'कोहळी मालगुजारांनी १५व्या ते १९व्या शतकादरम्यान विदर्भात ३,०००+ तलाव बांधले असल्याचे दस्तावेजीकरण.',
        icon: 'fa-microscope',
        color: '#2d6a4f',
        available: false,
        related_page: '#'
    }
],

    // ============================================================
    // GAZETTEERS DATA
    // ============================================================
    gazetteers: [
        {
                "id": 1,
                "year": "Colonial Period",
                "year_mr": "ब्रिटिश कालखंड",
                "title_en": "Bhandara District Gazetteer",
                "title_mr": "भंडारा जिल्हा गॅझेटिअर",
                "subtitle_en": "Central Provinces District Gazetteers",
                "subtitle_mr": "सेंट्रल प्रॉव्हिन्सेस जिल्हा गॅझेटिअर",
                "region_en": "Bhandara",
                "region_mr": "भंडारा",
                "region_key": "bhandara",
                "type_en": "District Gazetteer",
                "type_mr": "जिल्हा गॅझेटिअर",
                "badge_en": "Historical Government Publication",
                "badge_mr": "ऐतिहासिक सरकारी प्रकाशन",
                "badge_class": "cat-government",
                "desc_en": "Historical Bhandara District Gazetteer material provides information about the district's population, agriculture, social organization, economy, administration and rural life. References relevant to the Kohli community form part of this wider regional historical record.",
                "desc_mr": "भंडारा जिल्हा गॅझेटिअरमधील ऐतिहासिक सामग्रीमध्ये जिल्ह्याची लोकसंख्या, शेती, सामाजिक रचना, अर्थव्यवस्था, प्रशासन आणि ग्रामीण जीवनासंबंधी माहिती आढळते. कोहळी समाजाशी संबंधित संदर्भ या व्यापक प्रादेशिक ऐतिहासिक नोंदीचा भाग आहेत.",
                "source_status_en": "Reference Requires Page-Level Verification",
                "source_status_mr": "संदर्भ पडताळणी आवश्यक",
                "source_status_class": "badge-status-verify-page",
                "page_reference_en": "Page reference: To be verified",
                "page_reference_mr": "पृष्ठ संदर्भ: पडताळणी आवश्यक",
                "significance_en": "Provides valuable historical context on rural administration, agriculture, and village life in Bhandara district.",
                "significance_mr": "भंडारा जिल्ह्यातील ग्रामीण प्रशासन, शेती आणि समाजजीवनाचा महत्त्वपूर्ण ऐतिहासिक संदर्भ प्रदान करते.",
                "relevance_en": "Documents the historical presence, agricultural traditions, and settlements in the Bhandara region within wider administrative records.",
                "relevance_mr": "प्रशासकीय नोंदींमध्ये भंडारा परिसरातील ऐतिहासिक अस्तित्व, कृषी परंपरा आणि वसाहतींचे दस्तऐवजीकरण.",
                "icon": "fa-book-bookmark",
                "color": "#006699",
                "available": false,
                "related_page": "#"
        },
        {
                "id": 2,
                "year": "1909",
                "year_mr": "१९०९",
                "title_en": "Chanda District Gazetteer",
                "title_mr": "चांदा जिल्हा गॅझेटिअर",
                "subtitle_en": "Chandrapur — historical name: Chanda",
                "subtitle_mr": "चंद्रपूर — ऐतिहासिक नाव: चांदा",
                "region_en": "Chanda / Chandrapur",
                "region_mr": "चांदा / चंद्रपूर",
                "region_key": "chanda",
                "type_en": "District Gazetteer",
                "type_mr": "जिल्हा गॅझेटिअर",
                "badge_en": "Historical Government Publication",
                "badge_mr": "ऐतिहासिक सरकारी प्रकाशन",
                "badge_class": "cat-government",
                "desc_en": "The Chanda District Gazetteer provides historical information about the region's communities, agriculture, economy, water resources and administration. Kohli/Kohri-related references should be understood within this broader regional historical context.",
                "desc_mr": "चांदा जिल्हा गॅझेटिअरमध्ये प्रदेशातील समाजजीवन, शेती, अर्थव्यवस्था, जलस्रोत आणि प्रशासनासंबंधी ऐतिहासिक माहिती आढळते. कोहळी/कोहरी समाजाशी संबंधित उल्लेख या व्यापक प्रादेशिक ऐतिहासिक संदर्भात समजून घ्यावेत.",
                "source_status_en": "Historical Reference",
                "source_status_mr": "ऐतिहासिक संदर्भ",
                "source_status_class": "badge-status-reference",
                "page_reference_en": "Page reference: To be verified",
                "page_reference_mr": "पृष्ठ संदर्भ: पडताळणी आवश्यक",
                "significance_en": "Comprehensive 1909 colonial district gazetteer detailing communities, water resources, and revenue administration of Chanda.",
                "significance_mr": "चांदा जिल्ह्यातील समाज, जलव्यवस्थापन आणि महसूल प्रशासनाचे १९०९ मधील सर्वसमावेशक गॅझेटिअर.",
                "relevance_en": "Mentions regional communities and irrigation traditions of the Chandrapur region within period administrative records.",
                "relevance_mr": "चंद्रपूर क्षेत्रातील समुदाय आणि जलव्यवस्थापन परंपरांचा काळाच्या नोंदीनुसार उल्लेख.",
                "icon": "fa-book-open",
                "color": "#1b7a43",
                "available": false,
                "related_page": "#"
        },
        {
                "id": 3,
                "year": "1973",
                "year_mr": "१९७३",
                "title_en": "Maharashtra State Gazetteer — Chandrapur District",
                "title_mr": "महाराष्ट्र राज्य गॅझेटिअर — चंद्रपूर जिल्हा",
                "subtitle_en": "Revised Edition (State Gazetteer)",
                "subtitle_mr": "सुधारित आवृत्ती (राज्य गॅझेटिअर)",
                "region_en": "Chandrapur",
                "region_mr": "चंद्रपूर",
                "region_key": "state-gazetteer",
                "type_en": "State Gazetteer",
                "type_mr": "राज्य गॅझेटिअर",
                "badge_en": "State Gazetteer",
                "badge_mr": "राज्य गॅझेटिअर",
                "badge_class": "cat-state",
                "desc_en": "The revised Maharashtra State Gazetteer for Chandrapur District documents regional history, society, agriculture, economy and administration. It forms part of the later state-level historical reference material relevant to the region.",
                "desc_mr": "महाराष्ट्र राज्य गॅझेटिअरच्या चंद्रपूर जिल्ह्याच्या सुधारित आवृत्तीत प्रदेशाचा इतिहास, समाजजीवन, शेती, अर्थव्यवस्था आणि प्रशासन यासंबंधी माहिती संकलित करण्यात आली आहे. हे प्रादेशिक इतिहासाच्या पुढील कालखंडातील महत्त्वाचे संदर्भसाहित्य आहे.",
                "source_status_en": "Historical Reference",
                "source_status_mr": "ऐतिहासिक संदर्भ",
                "source_status_class": "badge-status-reference",
                "page_reference_en": "Page reference: To be verified",
                "page_reference_mr": "पृष्ठ संदर्भ: पडताळणी आवश्यक",
                "significance_en": "Post-independence revised state-level documentation providing updated historical and sociological overview of Chandrapur district.",
                "significance_mr": "स्वातंत्र्योत्तर काळातील सुधारित राज्यस्तरीय दस्तऐवजीकरण, ज्यामध्ये चंद्रपूर जिल्ह्याचा ऐतिहासिक व सामाजिक आढावा आहे.",
                "relevance_en": "State-level publication documenting district heritage, history, and community backgrounds.",
                "relevance_mr": "जिल्हा वारसा, इतिहास आणि सामाजिक पार्श्वभूमीची नोंद असलेले राज्यस्तरीय प्रकाशन.",
                "icon": "fa-landmark",
                "color": "#b45309",
                "available": false,
                "related_page": "#"
        },
        {
                "id": 4,
                "year": "Colonial Period",
                "year_mr": "ब्रिटिश कालखंड",
                "title_en": "Balaghat District Gazetteer",
                "title_mr": "बालाघाट जिल्हा गॅझेटिअर",
                "subtitle_en": "Central Provinces District Gazetteers",
                "subtitle_mr": "सेंट्रल प्रॉव्हिन्सेस जिल्हा गॅझेटिअर",
                "region_en": "Balaghat, Madhya Pradesh",
                "region_mr": "बालाघाट, मध्य प्रदेश",
                "region_key": "balaghat",
                "type_en": "District Gazetteer",
                "type_mr": "जिल्हा गॅझेटिअर",
                "badge_en": "Historical Regional Publication",
                "badge_mr": "ऐतिहासिक प्रादेशिक प्रकाशन",
                "badge_class": "cat-regional",
                "desc_en": "Historical Balaghat District Gazetteer material provides regional context for communities, agriculture, settlements and administration in the Balaghat area.",
                "desc_mr": "बालाघाट जिल्हा गॅझेटिअरमधील ऐतिहासिक सामग्रीमध्ये बालाघाट परिसरातील समाज, शेती, वसाहती आणि प्रशासनासंबंधी प्रादेशिक माहिती आढळते.",
                "source_status_en": "Reference Requires Page-Level Verification",
                "source_status_mr": "संदर्भ पडताळणी आवश्यक",
                "source_status_class": "badge-status-verify-page",
                "page_reference_en": "Page reference: To be verified",
                "page_reference_mr": "पृष्ठ संदर्भ: पडताळणी आवश्यक",
                "significance_en": "Provides cross-border regional context for Wainganga valley settlements and historical communities in Balaghat.",
                "significance_mr": "वैनगंगा खोऱ्यातील वसाहती आणि बालाघाट भागातील ऐतिहासिक समुदायांचा आंतरराज्यीय संदर्भ.",
                "relevance_en": "Regional administrative material covering agricultural practices and village settlements across the Wainganga basin.",
                "relevance_mr": "वैनगंगा खोऱ्यातील शेती आणि ग्रामवसाहतींशी संबंधित प्रादेशिक प्रशासकीय नोंदी.",
                "icon": "fa-map-marked-alt",
                "color": "#4338ca",
                "available": false,
                "related_page": "#"
        },
        {
                "id": 5,
                "year": "Historical Period",
                "year_mr": "ऐतिहासिक कालखंड",
                "title_en": "Central Provinces Gazetteer References",
                "title_mr": "सेंट्रल प्रॉव्हिन्सेस गॅझेटिअर संदर्भ",
                "subtitle_en": "Provincial Series & Administrative Reports",
                "subtitle_mr": "प्रांतीय मालिका व प्रशासकीय अहवाल",
                "region_en": "Central Provinces",
                "region_mr": "सेंट्रल प्रॉव्हिन्सेस",
                "region_key": "central-provinces",
                "type_en": "Historical Government Publication",
                "type_mr": "ऐतिहासिक सरकारी प्रकाशन",
                "badge_en": "Historical Government Publication",
                "badge_mr": "ऐतिहासिक सरकारी प्रकाशन",
                "badge_class": "cat-government",
                "desc_en": "Gazetteer and administrative publications from the Central Provinces provide historical context for communities and rural society in the region where Kohli/Kohri populations were recorded.",
                "desc_mr": "Central Provinces काळातील गॅझेटिअर आणि प्रशासकीय प्रकाशनांमधून त्या प्रदेशातील समुदाय आणि ग्रामीण समाजजीवनाचा ऐतिहासिक संदर्भ मिळतो. उपलब्ध संशोधनामध्ये कोहळी/कोहरी समाजाशी संबंधित उल्लेख या साहित्याच्या माध्यमातून अभ्यासले जातात.",
                "source_status_en": "Source Supplied for Research",
                "source_status_mr": "संशोधनासाठी उपलब्ध संदर्भ",
                "source_status_class": "badge-status-research",
                "page_reference_en": "Page reference: To be verified",
                "page_reference_mr": "पृष्ठ संदर्भ: पडताळणी आवश्यक",
                "significance_en": "Broad territorial administrative records covering the early ethnological, agricultural, and revenue framework of Central Provinces.",
                "significance_mr": "मध्य प्रांतातील सुरुवातीच्या सामाजिक, कृषी आणि महसूल रचनेचा व्यापक प्रादेशिक दस्तऐवज.",
                "relevance_en": "Historical references to Kohli/Kohri populations in wider Central India administrative records.",
                "relevance_mr": "मध्य भारतातील प्रशासकीय नोंदींमध्ये आढळणारे कोहळी/कोहरी समाजाशी संबंधित संदर्भ.",
                "icon": "fa-scroll",
                "color": "#0f766e",
                "available": false,
                "related_page": "#"
        }
],
    districts: [
        {
            id: 1,
            name_en: 'Bhandara',
            name_mr: 'भंडारा',
            subtitle_en: 'District of Lakes (तलावांचा जिल्हा)',
            subtitle_mr: 'तलावांचा जिल्हा',
            villages_count: 142,
            tanks_count: 850,
            desc_en: 'Bhandara is world-renowned for hundreds of ancient Malguzari tanks constructed by Kohli ancestors, serving as the cradle of indigenous paddy farming.',
            desc_mr: 'भंडारा जिल्हा हा कोहळी पूर्वजांनी बांधलेल्या शेकडो मालगुजारी तलावांसाठी जगभर प्रसिद्ध असून तो पारंपरिक भातशेतीचा मुख्य केंद्र आहे.',
            image: 'images/hero_stepwell.jpg',
            representative: 'Shri. Rameshji Kohli (District President)',
            phone: '+91 98230 12345',
            office: 'Kohli Samaj Bhavan, Main Road, Bhandara',
            villages: [
                { name_en: 'Pauni', name_mr: 'पवनी', tank_en: 'Navalgaon Malguzari Lake', tank_mr: 'नवलगाव मालगुजारी तलाव' },
                { name_en: 'Sakoli', name_mr: 'साकोली', tank_en: 'Bhadanga Water Tank', tank_mr: 'भडंगा जल तलाव' },
                { name_en: 'Lakhandur', name_mr: 'लाखांदूर', tank_en: 'Ashti Bhandara', tank_mr: 'आष्टी बंधारा' },
                { name_en: 'Mohadi', name_mr: 'मोहाडी', tank_en: 'Kardi Water Channel', tank_mr: 'करडी जलवाहिनी' },
                { name_en: 'Tumsar', name_mr: 'तुमसर', tank_en: 'Silewada Reservoir', tank_mr: 'सिलेवाडा जलाशय' }
            ]
        },
        {
            id: 2,
            name_en: 'Gondia',
            name_mr: 'गोंदिया',
            subtitle_en: 'Rice Bowl & Tank Capital',
            subtitle_mr: 'भाताचे कोठार व जलसमृद्धी',
            villages_count: 135,
            tanks_count: 920,
            desc_en: 'Famous for rich paddy fields irrigated by interconnected traditional water channels, stepwells, and ancient earthen dams.',
            desc_mr: 'पारंपरिक जलवाहिन्या, विहिरी आणि मातीच्या बंधाऱ्यांनी सिंचित केलेल्या समृद्ध भातशेतीसाठी प्रसिद्ध.',
            image: 'images/water_lake.jpg',
            representative: 'Shri. Sureshji Kohli (Gondia Representative)',
            phone: '+91 98231 67890',
            office: 'Samaj Seva Kendra, Civil Lines, Gondia',
            villages: [
                { name_en: 'Salekasa', name_mr: 'सालेकसा', tank_en: 'Hajari Water Reservoir', tank_mr: 'हजारी जलाशय' },
                { name_en: 'Goregaon', name_mr: 'गोरेगाव', tank_en: 'Katemajra Bhandara', tank_mr: 'काटेमाजरा बंधारा' },
                { name_en: 'Deori', name_mr: 'देवरी', tank_en: 'Chichgarh Tank', tank_mr: 'चिचगड तलाव' },
                { name_en: 'Arjuni Morgaon', name_mr: 'अर्जुनी मोरगाव', tank_en: 'Itiadoh Feeder Channel', tank_mr: 'इटियाडोह फीडर' }
            ]
        },
        {
            id: 3,
            name_en: 'Gadchiroli',
            name_mr: 'गडचिरोली',
            subtitle_en: 'Forest & River Heritage',
            subtitle_mr: 'वन व नदी संस्कृती',
            villages_count: 85,
            tanks_count: 410,
            desc_en: 'Forest-rich district with deep-rooted community traditions, herbal agriculture, and nature conservation practices.',
            desc_mr: 'वनसमृद्ध जिल्हा ज्यामध्ये कोहळी समाजाची सेंद्रिय शेती, वनौषधी व निसर्ग संवर्धनाची परंपरा आहे.',
            image: 'images/history_arch.jpg',
            representative: 'Shri. Prakashji Kohli (Gadchiroli Executive)',
            phone: '+91 98232 45678',
            office: 'Kohli Community Center, Armori Road, Gadchiroli',
            villages: [
                { name_en: 'Armori', name_mr: 'आरमोरी', tank_en: 'Wainganga Feeder Dam', tank_mr: 'वैनगंगा बंधारा' },
                { name_en: 'Kurkheda', name_mr: 'कुरखेडा', tank_en: 'Palasgaon Water Tank', tank_mr: 'पळसगाव तलाव' },
                { name_en: 'Dhanora', name_mr: 'धानोरा', tank_en: 'Kanhalgaon Reservoir', tank_mr: 'कान्हाळगाव जलाशय' }
            ]
        },
        {
            id: 4,
            name_en: 'Chandrapur',
            name_mr: 'चंद्रपूर',
            subtitle_en: 'Historic Forts & Water Engineering',
            subtitle_mr: 'ऐतिहासिक किल्ले व जल अभियांत्रिकी',
            villages_count: 95,
            tanks_count: 610,
            desc_en: 'Home to historic stone dams, ancient Gond-era settlement records, and vibrant community youth organizations.',
            desc_mr: 'ऐतिहासिक दगडाचे बंधारे, गोंडकालीन अभिलेख आणि सक्रिय युवक संघटनांचे केंद्र.',
            image: 'images/culture_tradition.jpg',
            representative: 'Shri. Vilasji Kohli (Chandrapur President)',
            phone: '+91 98233 89012',
            office: 'Kohli Samaj Bhavan, Mul Road, Chandrapur',
            villages: [
                { name_en: 'Nagbhid', name_mr: 'नागभीड', tank_en: 'Ghadbori Historic Tank', tank_mr: 'घोडझरी ऐतिहासिक तलाव' },
                { name_en: 'Brahmapuri', name_mr: 'ब्रह्मपुरी', tank_en: 'Ashti Irrigation Channel', tank_mr: 'आष्टी सिंचन वाहिनी' },
                { name_en: 'Sindewahi', name_mr: 'सिंदेवाही', tank_en: 'Nawargaon Malguzari Dam', tank_mr: 'नवरगाव मालगुजारी बंधारा' }
            ]
        },
        {
            id: 5,
            name_en: 'Balaghat',
            name_mr: 'बालाघाट',
            subtitle_en: 'Border Region & Agriculture',
            subtitle_mr: 'सीमावर्ती भाग व कृषी संस्कृती',
            villages_count: 64,
            tanks_count: 380,
            desc_en: 'Significant Kohli population in Madhya Pradesh border region known for sustainable farming techniques and cultural harmony.',
            desc_mr: 'मध्य प्रदेश सीमावर्ती भागातील समृद्ध कोहळी समाज जो सेंद्रिय शेती व सामाजिक सलोख्यासाठी प्रसिद्ध आहे.',
            image: 'images/document_scroll.jpg',
            representative: 'Shri. Ashokji Kohli (Balaghat Representative)',
            phone: '+91 98234 34567',
            office: 'Kohli Seva Mandal, Main Market, Waraseoni, Balaghat',
            villages: [
                { name_en: 'Waraseoni', name_mr: 'वाराशिवनी', tank_en: 'Rampaily Tank', tank_mr: 'रामपायली तलाव' },
                { name_en: 'Katangi', name_mr: 'कटंगी', tank_en: 'Chandan River Dam', tank_mr: 'चंदन नदी बंधारा' },
                { name_en: 'Lalburra', name_mr: 'लालबर्रा', tank_en: 'Garra Feeder Lake', tank_mr: 'गर्रा तलाव' }
            ]
        }
    ],
    news: [
        {
            id: 1,
            day: '04',
            month_en: 'MAY',
            month_mr: 'मे',
            title_en: 'Registration Open for Grand Samaj Melava 2026',
            title_mr: 'समाज मेळाव्याची नोंदणी सुरू',
            subtitle_en: 'Bhandara, Date: 15 June 2026',
            subtitle_mr: 'भंडारा, दिनांक १५ जून २०२६',
            details_en: 'Delegate registrations for the annual assembly are now active. All district committees are requested to coordinate participation.'
        },
        {
            id: 2,
            day: '28',
            month_en: 'MAY',
            month_mr: 'मे',
            title_en: 'Educational Guidance & Scholarship Camp',
            title_mr: 'शैक्षणिक मार्गदर्शन शिबीर',
            subtitle_en: 'Date: 22 June 2026',
            subtitle_mr: 'दिनांक २२ जून २०२६',
            details_en: 'Free guidance on MPSC, UPSC, Engineering, Medical admissions, and student financial aid schemes.'
        },
        {
            id: 3,
            day: '15',
            month_en: 'APR',
            month_mr: 'एप्रिल',
            title_en: 'Vadhu-Var Parichay Booklet Submission',
            title_mr: 'वधू-वर परिचय मेळावा नोंदणी',
            subtitle_en: 'Registration ongoing',
            subtitle_mr: 'नोंदणी सुरू',
            details_en: 'Submit online candidate profiles for inclusion in the upcoming print and digital directory.'
        }
    ],
    gallery: [
        { id: 1, image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', caption_en: 'Navegaon Bandh Lake (Kolu Patel Kohli)', caption_mr: 'नवेगाव बांध तलाव (कोळू पटेल कोहळी)' },
        { id: 2, image: 'images/water_lake.jpg', caption_en: 'Scenic Water Reservoir Bhandara', caption_mr: 'जलसंवर्धन बंधारा' },
        { id: 3, image: 'images/history_arch.jpg', caption_en: 'Heritage Arch Archway', caption_mr: 'ऐतिहासिक वास्तू' },
        { id: 4, image: 'images/culture_tradition.jpg', caption_en: 'Community Gathering & Celebration', caption_mr: 'सांस्कृतिक कार्यक्रम' },
        { id: 5, image: 'images/document_scroll.jpg', caption_en: 'Archival Records & Manuscripts', caption_mr: 'ऐतिहासिक दस्तऐवज' },
        { id: 6, image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', caption_en: 'Historic Malguzari Water System Vidarbha', caption_mr: 'ऐतिहासिक मालगुजारी जलव्यवस्थापन सिंचन' }
    ]
};

// Helper function to load data from localStorage or fallback to initialData
function getPortalData() {
    const saved = localStorage.getItem('kohli_samaj_portal_data');
    if (saved) {
        try {
            const parsed = JSON.parse(saved);
            parsed.districts = initialData.districts;
            return parsed;
        } catch (e) {
            console.error('Failed to parse saved portal data', e);
        }
    }
    return initialData;
}

// Helper function to save data to localStorage (Simulating .NET API persistence)
function savePortalData(data) {
    localStorage.setItem('kohli_samaj_portal_data', JSON.stringify(data));
}
